version: '3'
services:
  web:
    image: products
    ports:
      - 8080:8080
    depends_on:
      - db
    build: .
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRESS_PASSWORD: admin
volumes:
  data: